spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audition_db
    username: audition_user
    password: audition_pass
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.audition.platform: DEBUG
