app:
  version: 1.0.0-SNAPSHOT
  buildId: ""
  cors:
    allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"
  jwt:
    secret: "${JWT_SECRET:change-me-in-production-min-32-chars}"
    expiration-ms: 86400000  # 24h

spring:
  application:
    name: audition-platform-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/audition
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
